server.port=8080
# Route to auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/admin/users/**

# Route to account-service
spring.cloud.gateway.routes[1].id=account-service
spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/accounts/**,/api/beneficiaries/**,/api/teller/**,/api/admin/accounts/**

# Route to transaction-service
spring.cloud.gateway.routes[2].id=transaction-service
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/transactions/**,/api/admin/transactions/**

app.jwt.secret=NeoBankSuperSecretKey2024ForJWTTokenGenerationMustBe256BitsLong
app.jwt.expiration-ms=86400000   24 hours

spring.main.allow-bean-definition-overriding=true

spring.main.web-application-type=reactive
